# Generated by Django 4.1.1 on 2022-09-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HealthCareWorker",
            fields=[
                (
                    "rpps_number",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("last_name", models.CharField(default="", max_length=100)),
                ("first_name", models.CharField(default="", max_length=100)),
                ("profession_name", models.CharField(default="", max_length=100)),
            ],
        ),
    ]
