# Generated by Django 4.1.1 on 2022-09-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_directory", "0003_alter_healthcareworker_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthcareworker",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="healthcareworker",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="healthcareworker",
            name="profession_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
