# Generated by Django 4.1.1 on 2022-09-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_directory", "0006_healthcareworker_organizations"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("finess", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(blank=True, default="", max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="healthcareworker",
            old_name="organizations",
            new_name="organizations_finess",
        ),
    ]
