# Generated by Django 4.1.1 on 2022-09-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_directory", "0007_organization_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="healthcareworker",
            old_name="organizations_finess",
            new_name="finess_list",
        ),
        migrations.RenameField(
            model_name="organization",
            old_name="name",
            new_name="registered_name",
        ),
    ]
